### PR TITLE
Display a custom 404 page

### PR DESCRIPTION
**Pull request by sethlivingston**
- Display an intentional 404 error page to prevent content spoofing

### CODE REVIEW

**Review by eric-moov — APPROVED** [review]

**Comment by adamdecaf** [comment]
@sethlivingston does this address the HackerOne report?

**Comment by jeff18997** [comment]
@adamdecaf I believe this does cure it.  I see we get an Error 502 from cloudflare now instead of the reflected text et al.  Jeremiah is confirming and we will return to HackerOne and have the hacker that found it confirm as well.  Thank you @sethlivingston

**Comment by adamdecaf** [comment]
Perfecto, thanks!

**Comment by adamdecaf** [comment]
Do we know if HackerOne and Github can integrate? It would be cool to show this PR is directly related to a security fix.

**Pull request merged**
